"$schema" = "./node_modules/wrangler/config-schema.json"
name = "lifetime-store"
pages_build_output_dir = "./public"
compatibility_date = "2026-04-05"

[[d1_databases]]
binding = "DB"
database_name = "lifetime_store_db"
database_id = "bc222039-babe-4e22-bf21-95d4c5017c32"
preview_database_id = "bc222039-babe-4e22-bf21-95d4c5017c32"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "lifetime-products"

[vars]
BRAND_NAME = "Lifetime"
BRAND_EMAIL = "support@lifetime-store.shop"
R2_PUBLIC_BASE_URL = "https://pub-9e90e5f450064cbeb75d5403e2acd4ed.r2.dev"
PAYSTACK_PUBLIC_KEY = "pk_live_77d5b9a1e47bfa36151c733925cecb01515666aa"
ALERT_TO_EMAIL = "support@lifetime-store.shop"
MAIL_FROM_EMAIL = "orders@lifetime-store.shop"
SUPPORT_EMAIL = "support@lifetime-store.shop"
ORDERS_EMAIL = "orders@lifetime-store.shop"
