"$schema" = "./node_modules/wrangler/config-schema.json"
name = "lifetime-store"
pages_build_output_dir = "./public"
compatibility_date = "2026-04-05"

[[d1_databases]]
binding = "DB"
database_name = "lifetime_store_db"
database_id = "bc222039-babe-4e22-bf21-95d4c5017c32"
preview_database_id = "bc222039-babe-4e22-bf21-95d4c5017c32"

[vars]
BRAND_NAME = "Lifetime"
BRAND_EMAIL = "lifetimestore@zohomail.com"
