import { error, ok, optionsResponse } from "../../_lib/response.js";

function authenticityStatus(item) {
  if (!item) return { valid: false, authenticity: "unknown", message: "This code does not exist in the Lifetime verification registry." };
  if (item.status === "active") return { valid: true, authenticity: "verified", message: "Authentic Lifetime item." };
  if (["generated", "printed", "attached", "received", "draft"].includes(item.status)) {
    return { valid: false, authenticity: "pending_activation", message: "This code was generated by Lifetime but is not active for sale yet." };
  }
  if (["blocked", "void", "archived"].includes(item.status)) {
    return { valid: false, authenticity: "blocked", message: "This code exists but has been blocked, replaced, or archived." };
  }
  return { valid: false, authenticity: "unknown", message: "This code exists but is not currently available." };
}

export async function onRequestOptions() {
  return optionsResponse();
}

export async function onRequestGet(context) {
  const code = decodeURIComponent(context.params.code || "").trim();
  if (!code) return error("No authenticity code provided.", 400);

  const item = await context.env.DB.prepare(`
    SELECT
      ac.id,
      ac.serial_code,
      ac.status,
      ac.first_scan_at,
      ac.scan_count,
      ac.activated_at,
      b.batch_code,
      b.factory_name,
      b.manufactured_at,
      p.name AS product_name,
      p.slug,
      COALESCE(v.color, '') AS color,
      COALESCE(v.size, '') AS size
    FROM auth_codes ac
    JOIN products p ON p.id = ac.product_id
    LEFT JOIN variants v ON v.id = ac.variant_id
    JOIN batches b ON b.id = ac.batch_id
    WHERE ac.serial_code = ?
    LIMIT 1
  `).bind(code).first();

  if (!item) {
    return ok({
      valid: false,
      authenticity: "unknown",
      message: "This code does not exist in the Lifetime verification registry.",
      item: null
    });
  }

  const result = authenticityStatus(item);

  if (result.authenticity === "verified") {
    await context.env.DB.prepare(`
      UPDATE auth_codes
      SET scan_count = scan_count + 1,
          first_scan_at = COALESCE(first_scan_at, CURRENT_TIMESTAMP)
      WHERE id = ?
    `).bind(item.id).run();

    try {
      await context.env.DB.prepare(`
        INSERT INTO verification_logs (auth_code_id, serial_code, result, source, created_at)
        VALUES (?, ?, 'verified', 'public_verify', CURRENT_TIMESTAMP)
      `).bind(item.id, item.serial_code).run();
    } catch {
      // verification_logs table is optional until migration 0004 is run
    }

    item.scan_count = Number(item.scan_count || 0) + 1;
    item.first_scan_at = item.first_scan_at || new Date().toISOString();
  }

  return ok({ ...result, item });
}
